version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'qwerty'

  backend:
    build: ./backend
    privileged: true
    restart: always
    expose:
      - 8080
    depends_on:
      - db
    command: bash -c "
        ./wait-for-postgres.sh db
        python manage.py makemigrations &&
        python manage.py migrate && 
        gunicorn config.wsgi -b 0.0.0.0:8080
      "
  nginx:
    build: ./nginx
    privileged: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    privileged: true
    restart: always
    ports:
      - 80:80
    depends_on:
      - nginx
