# Generated by Django 3.2.14 on 2022-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('link_to_git', models.URLField(verbose_name='Link to git')),
                ('name', models.CharField(max_length=50, verbose_name='Project name')),
                ('discroption', models.TextField(blank=True, null=True, verbose_name='Discription')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ToDo_noteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('discroption', models.TextField(blank=True, null=True, verbose_name='Discription')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed note')),
            ],
            options={
                'verbose_name': 'ToDo note',
                'verbose_name_plural': 'ToDo notes',
            },
        ),
    ]
